### ISSUE TITLE
Unable to download the csv Example

### ISSUE THREAD

**Issue by LocutusOfPenguin** [Eilon/dotnetConf-BrickTracker#1]
Hi,
great talk!

I'm fully aware that "brickset" is not your side. But i can't find this "download csv" Button at all (even i have a large screen) mentioned on your readme file.
Can you provide a small csv file to your github to make it easier to start up - just to have some sample data?

Thanks!

**Comment by Eilon** [comment]
Hi @LocutusOfPenguin , I added some sample CSV files to the root of this repo:

* 2021 Harry Potter sets: https://raw.githubusercontent.com/Eilon/dotnetConf-BrickTracker/main/HarryPotterSets.csv
* 2021 Lord of the Rings sets: https://raw.githubusercontent.com/Eilon/dotnetConf-BrickTracker/main/LOTR.csv

And I just checked, and it seems that the CSV download feature is only available if you're logged into the BrickSet site! So if you want, you could sign up (free) to be able to download the results of a custom query. My apologies for not noticing that earlier!

**Comment by Eilon** [comment]
Also, I updated the readme in this repo to clarify this and add the links. Thanks for the feedback!
